
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-exporter
  labels:
    app: network-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      labels:
        app: network-exporter
    spec:
      containers:
        - name: network-exporter
          image: syepes/network_exporter
          args: ["/app/network_exporter", "--log.level=debug"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - containerPort: 9427
          volumeMounts:
            - name: config-volume
              mountPath: /app/cfg/network_exporter.yml
              subPath: network_exporter.yml
      volumes:
        - name: config-volume
          configMap:
            name: network-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-exporter-config
  labels:
    app: network-exporter
data:
  network_exporter.yml: |
    # Main Config
    conf:
      refresh: 15m
      nameserver_timeout: 250ms # Optional

    # Specific Protocol settings
    icmp:
      interval: 3s
      timeout: 1s
      count: 6

    mtr:
      interval: 3s
      timeout: 500ms
      max-hops: 30
      count: 6

    tcp:
      interval: 3s
      timeout: 1s

    http_get:
      interval: 15m
      timeout: 5s

    # Target list and settings
    targets:
      - name: pythontest
        host: 192.168.100.172:8000
        type: TCP
      - name: github
        host: https://github.com/syepes
        type: HTTPGet
       
          
        
---
apiVersion: v1
kind: Service
metadata:
  name: network-exporter
  labels:
    app: network-exporter
spec:
  selector:
    app: network-exporter
  ports:
    - protocol: TCP
      port: 9427
      targetPort: 9427
