
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-exporter
  labels:
    app: network-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      labels:
        app: network-exporter
    spec:
      containers:
        - name: network-exporter
          image: syepes/network_exporter
          args: ["/app/network_exporter", "--log.level=debug"]
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          ports:
            - containerPort: 9427
          volumeMounts:
            - name: config-volume
              mountPath: /app/cfg/network_exporter.yml
              subPath: network_exporter.yml
      volumes:
        - name: config-volume
          configMap:
            name: network-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-exporter-config
  labels:
    app: network-exporter
data:
  network_exporter.yml: |
    # Main Config
    conf:
      refresh: 15m
      nameserver: 192.168.0.1:53 # Optional
      nameserver_timeout: 250ms # Optional

    # Specific Protocol settings
    icmp:
      interval: 3s
      timeout: 1s
      count: 6

    mtr:
      interval: 3s
      timeout: 500ms
      max-hops: 30
      count: 6

    tcp:
      interval: 3s
      timeout: 1s

    http_get:
      interval: 15m
      timeout: 5s

    # Target list and settings
    targets:
      - name: internal
        host: 192.168.0.1
        type: ICMP
        probe:
          - hostname1
          - hostname2
        labels:
          dc: home
          rack: a1
      - name: google-dns1
        host: 8.8.8.8
        type: ICMP
      - name: google-dns2
        host: 8.8.4.4
        type: MTR
      - name: cloudflare-dns
        host: 1.1.1.1
        type: ICMP+MTR
      - name: cloudflare-dns-https
        host: 1.1.1.1:443
        source_ip: 192.168.1.1
        type: TCP
      - name: download-file-64M
        host: http://test-debit.free.fr/65536.rnd
        type: HTTPGet
      - name: download-file-64M-proxy
        host: http://test-debit.free.fr/65536.rnd
        type: HTTPGet
        proxy: http://localhost:3128
