version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    networks:
      - web
    labels:
      - "traefik.enable=true"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: nginx
    ports:
     - "9000:80"
    networks:
      - web
    environment:
     - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Path(`/`)" # Rota baseada na URL /nginx
      - "traefik.http.routers.nginx.entrypoints=http"

networks:
  web:
    external: true