version: '3'

services:

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    volumes:
      - ../haproxy/haproxy-reverse-proxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "8404:8404"
  
  front-a:
    image:  traefik/whoami

  front-b:
    image:  traefik/whoami


networks:
  reverse-proxy:
    external: true
