version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ../nginx/nginx-reverse-proxy.conf:/etc/nginx/nginx.conf
      # - ./certs:/etc/nginx/certs
  
  front-a:
    image:  traefik/whoami

  front-b:
    image:  traefik/whoami

networks:
  reverse-proxy:
    external: true
