version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ../nginx/nginx-load-balancer.conf:/etc/nginx/nginx.conf

  front-a:
    image:  traefik/whoami

  front-b:
    image:  traefik/whoami

networks:
  reverse-proxy:
    external: true
