version: '3'

services:

  #############
  ## HAProxy ##
  #############

  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    volumes:
      - ../haproxy/haproxy-load-balancer.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "8404:8404"

  #########################
  ## front-a and front-b ##
  #########################
  
  front-a:
    image: nginx:latest
    expose:
      - 80
  
  front-b:
    image: nginx:latest
    expose:
      - 80

networks:
  reverse-proxy:
    external: true
