version: '3'
services:
  envoy-proxy:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ../envoy/envoy-load-balancer.yaml:/etc/envoy/envoy.yaml
    expose:
      - "8888"
      - "8001"
    ports:
      - "8888:8888"
      - "8001:8001"

  front-a:
    image: nginx
    environment:
     - NGINX_PORT=80

  front-b:
    image: nginx
    environment:
     - NGINX_PORT=80

